### ISSUE TITLE
Админ панель для распределения вещей по больницам

### ISSUE THREAD

**Issue by BupycHuk** [Entea/covid-supply-info#128]
Нужно сделать админ панель
* Дата распределения
* Кто выдал(Текстовое поле)
* Кто принял(Текстовое поле)
* Больница (many to one)
* Из каких пожертвований(many to many, optional)
* Детали(one to many)
  * Список необходимых вещей с количеством
* Статус(Подготовлено, Отправлено, Доставлено)

**Comment by isabek** [comment]
Много вопросов по этой задаче. 

Надо ли здесь сделать бухгалтерию?

Мне кажется нажо вести учет каким-то обзразом.

1. Кто дал? 
2. Кто получил? 
3. Сколько осталось?
4. Автоматически обновлять потребностей больниц.

**Comment by isabek** [comment]
5. Когда админ заходит най сайт он должен увидеть след. вещи.
  5.1. Объем оказанной помощи.
  5.2. Что у нас осталось.

**Comment by BupycHuk** [comment]
Согласен.
1 и 2 как часть этой задачи
3, 4 и 5 как отдельные задачи
Для задачи №4 нужно добавить функционал по расходу потребностей в больницах

**Comment by Entea** [comment]
по пункту 4: просьба не модифицировать данные, а считать баланс между "требуется" - "в наличии"
