### ISSUE TITLE
Добавить модальное окно

### ISSUE THREAD

**Issue by Diyahon** [Entea/covid-supply-info#40]
Нужно сверстать модальное окно
В проекте есть react-bootstrap его компонент модального окна можно использовать
капчу надо добавить еще

<img width="276" alt="Снимок экрана 2020-03-26 в 21 27 39" src="https://user-images.githubusercontent.com/9525715/77677212-92c15c80-6fb9-11ea-81e4-c61d62fc58c0.png">

**Comment by isabek** [comment]
@Diyahon не забудь добавить проверку на робота

**Comment by Entea** [comment]
@Diyahon я дам ключик recaptcha v2
