### ISSUE TITLE
CRUD для типов нужд больниц

### ISSUE THREAD

**Issue by Entea** [Entea/covid-supply-info#5]
Необходим справочник для типов нужд:
* id
* наименование (маска, перчатки, спирт, итд)
* мера (литры, штуки, килограммы)
* стоимость за единицу в сом.

**Comment by BupycHuk** [comment]
> стоимость за единицу в сом  
@Entea А нужно ли это обозначать в справочнике? При каждом закупе же может меняться

**Comment by Entea** [comment]
Пока хотя-бы так
