### ISSUE TITLE
CRUD для нужд больниц

### ISSUE THREAD

**Issue by Entea** [Entea/covid-supply-info#8]
Для каждой больницы, необходимо добавлять:
* Сколько на данный момент имеется
* Объем нужд
* Тип нужд
* Дата добавления

**Comment by adiletegemberdiev** [comment]
как назначить на себя?

**Comment by adiletegemberdiev** [comment]
ERROR: Permission to Entea/covid-supply-info.git denied to adiletegemberdiev. Could not read from remote repository. Please make sure you have the correct access rights and the repository exists.

не могу пушнуть, дайте плиз доступ
